package com.ua.viktor.amp.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ua.viktor.amp.model.Question;
import com.ua.viktor.amp.model.Choice;

import com.ua.viktor.amp.model.QuestionDao;
import com.ua.viktor.amp.model.ChoiceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig questionDaoConfig;
    private final DaoConfig choiceDaoConfig;

    private final QuestionDao questionDao;
    private final ChoiceDao choiceDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        questionDaoConfig = daoConfigMap.get(QuestionDao.class).clone();
        questionDaoConfig.initIdentityScope(type);

        choiceDaoConfig = daoConfigMap.get(ChoiceDao.class).clone();
        choiceDaoConfig.initIdentityScope(type);

        questionDao = new QuestionDao(questionDaoConfig, this);
        choiceDao = new ChoiceDao(choiceDaoConfig, this);

        registerDao(Question.class, questionDao);
        registerDao(Choice.class, choiceDao);
    }
    
    public void clear() {
        questionDaoConfig.getIdentityScope().clear();
        choiceDaoConfig.getIdentityScope().clear();
    }

    public QuestionDao getQuestionDao() {
        return questionDao;
    }

    public ChoiceDao getChoiceDao() {
        return choiceDao;
    }

}
