package com.ua.viktor.amp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ANSWERS.
 */
public class Answers {

    private Long id;
    /** Not-null value. */
    private String text;
    private Integer ID;

    public Answers() {
    }

    public Answers(Long id) {
        this.id = id;
    }

    public Answers(Long id, String text, Integer ID) {
        this.id = id;
        this.text = text;
        this.ID = ID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getText() {
        return text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText(String text) {
        this.text = text;
    }

    public Integer getID() {
        return ID;
    }

    public void setID(Integer ID) {
        this.ID = ID;
    }

}
